### ISSUE TITLE
wrong d.ts generated when importing same name classes with alias

### ISSUE THREAD

**Issue by hdmr14** [wessberg/rollup-plugin-ts#136] opened 2021-01-28 03:30 UTC
- Version: 1.3.8
- Rollup Version: 2.38.0
- TypeScript Version: 4.1.3

### Reproduction
1. create a class module with the same name in different named files  ([b.ts](https://repl.it/@hdmr14/wrong-type-declaration#b.ts) and [b2.ts](https://repl.it/@hdmr14/wrong-type-declaration#b2.ts))
2. import them to same place([index.ts](https://repl.it/@hdmr14/wrong-type-declaration#index.ts)) using alias
3. export something using them(it just re-exported them in Repl)
4. wrong d.ts generated(js is fine)

Here's Repl:
https://repl.it/@hdmr14/wrong-type-declaration
Config file:
https://repl.it/@hdmr14/wrong-type-declaration#rollup.config.js
Generated files:
https://repl.it/@hdmr14/wrong-type-declaration#out/index.d.ts
https://repl.it/@hdmr14/wrong-type-declaration#out/index.js

### Expected Behavior
it should be based on the generated js code.
```ts
declare class B {
}
declare class B$1 {
}
type B2 = B$1;
export { B, B2 };
```
or some BWrappers generated?

### Actual Behavior
unexpected `BWrapper` generated
```ts
declare class B {
    b(): void;
}
declare module BWrapper {
    export { B };
}
import B2 = BWrapper.B$0; // <= B$0 not declared
export { B, B2 };
```

**Comment by wessberg** [comment] 2021-04-13 19:15
That's definitely a bug. Thanks for the repro, I'll look into it.

As for why there's a `ModuleDeclaration` in there and we don't do a `TypeAliasDeclaration` such as you suggest (`type B2 = B$1`), there's actually a very good reason for it, [and you can read more about it here](https://github.com/wessberg/rollup-plugin-ts/issues/68#issuecomment-573468913). Classes are treated a little bit different than other types in TypeScript and type aliases cannot be instantiated.

**Comment by wessberg** [comment] 2021-04-13 19:52
This has been fixed and was caused by the deconflicting logic of the declaration bundler not handling `QualifiedName` nodes. A new version will be released on NPM shortly containing this fix.

**Closed** 2021-04-13 19:52 UTC
Labels: Bug
