### ISSUE TITLE
Empty .d.ts rollup emit regression in 1.2.28

### ISSUE THREAD

**Issue by ggoodman** [wessberg/rollup-plugin-ts#105] opened 2020-07-18 02:12 UTC
- Version: 1.2.28
- Rollup Version: 2.21.0
- Operating System and version (if applicable): MacOS 10.15.5
- Node Version (if applicable): 12.18.2
- Does it work with `tsc` (if applicable): N/A
- Typescript: `3.9.7`

### Reproduction

Using this plugin produces correct (as far as I can tell) `.d.ts` rollups for all submodules of [velcro](https://github.com/ggoodman/velcro).

However, upon upgrading to `1.2.28`, the emitted `.d.ts` files are empty and no errors appear to be emitted either.

Reproduction can be achieved by:

1. Clone ggoodman/velcro#8f6063e43fe3fdc01d06fd38fb82455026bf8ed7
2. `npm i`
3. `npx lerna bootstrap`
4. `npm run build`
5. Observe that `./dist/dist-main/index.d.ts` for `./packages/@velcro/bundler` is empty.

All sub-packages defer to the top-level rollup factory in `rollup.config.factory.js` so you shouldn't have to look further than that to see how this plugin is being instantiated.

### Expected Behavior

Produces a rolled-up `.d.ts` file

### Actual Behavior

Produces an empty `.d.ts` file without reporting any errors or warnings

Thanks for all your hard work on this!

**Comment by wessberg** [comment] 2020-07-20 08:31
Hey there. Thanks for submitting this issue. This is a duplicate of https://github.com/wessberg/rollup-plugin-ts/issues/103.

I added an entry in the FAQ explaining why this can happen: https://github.com/wessberg/rollup-plugin-ts#my-declaration-files-are-always-empty.

I think the reason why this is happening is that prior to v1.2.28, the plugin enforced a `baseUrl` of `"."`, which may break path mapping. The declaration file can turn out to be empty due to an internal unrecoverable error or an invalid internal folder structure.

To work around it while I'm investigating if I can fix this on the plugin-side, try following the tips of the FAQ entry. I'll keep this issue open while I'm investigating if this can be fixed in my end

**Comment by ggoodman** [comment] 2020-07-20 13:13
Hi @wessberg, I had indeed missed that FAQ entry.

I've taken a look at then entry and can confirm two things:

1. Each sub-package defines [`"include": ["src"]`](https://github.com/ggoodman/velcro/blob/77287ef4b84a721027328beae62579087d610312/packages/%40velcro/resolver/tsconfig.json#L9). Note that no `"exclude"` clauses are included; are they required even if having explicit `"include"`s?
2. All sub-packages' `dist` directories are [emptied before initiating a build](https://github.com/ggoodman/velcro/blob/77287ef4b84a721027328beae62579087d610312/package.json#L8).

**Comment by wessberg** [comment] 2020-07-20 13:22
Thanks for the update. Very strange indeed. I'll clone your repo and see what I can make of it :-)

**Comment by ggoodman** [comment] 2020-07-20 15:44
@wessberg one thing of note is that each of my sub-packages define [multiple rollup builds](https://github.com/ggoodman/velcro/blob/77287ef4b84a721027328beae62579087d610312/rollup.config.factory.js#L23-L131).

**Comment by wessberg** [comment] 2020-07-27 14:07
That's shouldn't be a problem, and I can see based on your repo that the problem persists with only a single output bundle.
Anyway, thanks to your repro, I've found and implemented a fix. I will release a new version shortly.

**Closed** 2020-07-27 14:06 UTC

**Comment by wessberg** [comment] 2020-07-28 07:35
[v1.2.29](https://github.com/wessberg/rollup-plugin-ts/releases/tag/v1.2.29) has been published now!

**Comment by ggoodman** [comment] 2020-07-28 12:28
Amazing! Works as advertised. ❤️
