### ISSUE TITLE
allowSyntheticDefaultImports: true breaking with this plugin

### ISSUE THREAD

**Issue by ccrowley96** [wessberg/rollup-plugin-ts#119] opened 2020-09-11 19:50 UTC
### Question
Throwing error: `[!] (plugin Typescript) TS2339: Property 'tz' does not exist on type 'typeof import("C:/Users/cocrowle/Documents/Repositories/tsiclient/node_modules/moment-timezone/moment-timezone")'.`

Before switching to this plugin:
`import moment from 'moment'` and `import moment from 'moment-timezone'` were working.  But this seems to have trouble processing umd bundles that don't have default exports like moment.

I've tried `import * as moment from 'moment-timezone'` and 

```js
import * as _momentTZ from 'moment-timezone'`
const momentTZ = _momentTZ
```

But `.tz` isn't being found on any of these imports.  I'm mostly not sure why this is flagging errors when the other typescript plugins seem fine with the syntax `import moment from 'moment'`.  That line will throw no default export found error.

Any idea why this may be happening?

**Comment by ccrowley96** [comment] 2020-09-11 20:03
I believe this is an issue with `allowSyntheticDefaultImports: true`.

**Comment by wessberg** [comment] 2020-09-11 21:36
Hi there. This plugin does not enforce any special rules regarding `allowSyntheticDefaultImports`.
As you also mention yourself, it is correct that if you want to write `import moment from "moment-timezone"` with TypeScript, you'll have to set `allowSyntheticDefaultImports: true` in your `tsconfig` to make TypeScript syntactically treat CommonJS-style assignments to the `exports` object as default exports.

I just set up a simple repo to test this out. It understands the import just fine: You can find it here: https://repl.it/@wessberg/moment-timezone.

If you are experiencing what you believe is a bug related to this plugin, please prepare a minimal repro that I can take a look at.

**Comment by wessberg** [comment] 2020-09-11 22:58
I just posted a long reply to the other issue you have submitted here: https://github.com/wessberg/rollup-plugin-ts/issues/118#issuecomment-691342147. Based on that, I believe I have a better understanding on the types of issues you are experiencing here.

You are actually experiencing two separate issues:

1. You are depending on a version of `moment-timezone` that doesn't ship typings. Because you set `allowJs: true` in your `tsconfig.json`, TypeScript doesn't complain about your import, but it will complain about trying to lookup the `tz` property on moment (such as you do in `src/UXClient/Utils.ts`). This diagnostic is rightly deported by this plugin, and is not a bug. Updating to the newest version of that library resolves this plugin, as `tz` is part of the typings.

2. Rollup is not able to find a default export inside the module `node_modules/moment-timezone/index.js`, even after @rollup/plugin-commonjs has attempted to rewrite it into ESM. That's why Rollup will complain about not being able to resolve a default export from within that file.

I think it is important that you understand where TypeScript stops and where Rollup begins here. [This answer](https://github.com/wessberg/rollup-plugin-ts/issues/113#issuecomment-686075384) I made on another issue explains it in great detail. `allowSyntheticDefaultImports` tells the TypeScript compiler to not complain when it sees such an import, which is why you won't see TypeScript complain about it, neither the language service for your editor, nor this plugin. But that has no relation to or impact whatsoever on how Rollup goes about resolving and bundling together your external dependencies, and there are lots of libraries that can be troublesome to inline with Rollup that are written in UMD/CommonJS.

I'll go ahead and close this issue and instead refer you to [this part of the Rollup documentation](https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module) that can help you with `moment-timezone`.

**Closed by wessberg** 2020-09-11 22:58 UTC
Labels: Needs reproduction, invalid

**Comment by ccrowley96** [comment] 2020-09-12 01:31
Wow, thank you for such in depth answers.  I really appreciate all of the effort that went into this.

What's confusing to me is that everything is bundled and works properly with rollup-plugin-typescript2.  When I exchanged that plugin for this one, these errors surfaced.

I made your suggested changes and it's definitely closer to a working build.  The CJS moment stuff just won't work, but I understand now that that's not a problem with this plugin.  Apologies for the false claim.  I'm new to the bundling / module js world.  It's a wild one.

It's **so** close to working too haha.  The typescript declaration files outputted by this plugin are amazing and perfectly fit my use case.  I just need to get moment working.  Hopefully we'll be utilizing this plugin as a core build dependency!

Thanks again for the help!  It's incredibly appreciated.
