### ISSUE TITLE
tsconfig.json - typescript target is not used

### ISSUE THREAD

**Issue by jarekcieslak** [wessberg/rollup-plugin-ts#11] opened 2019-03-08 13:59 UTC
Hi!

Whenever I try to set target in the tsconfig.json file it's not taken into account by the TypescriptService and compilation is done using default (es3).  

When I try to set "target": "es5" in my tsconfig.json and compile my code I see that target is being set to "es3" (which has code 0). I did a small investigation and it looks that the problem is function `getForcedScriptTargetOption` which is not taking into account tsconfig.json settings. it's using default settings for browserlist (> 0.5%, last 2 versions, Firefox ESR, not dead) and  produces in the end "es3".

My temporary solution was to set those settings in rollup config:
```
typescript({
      browserslist: ["chrome >= 50"],
      tsconfig: "./tsconfig.json"
    }),
```

**Comment by wessberg** [comment] 2019-03-09 07:09
HI there. Thanks or submitting this issue.
This is actually the intended behavior. If you provide a browserslist, or if a browserslist can be found in the root of your project, the Typescript target will be determined based on the Browserslist.

If you don't want the Typescript target to be determined by your Browserslist, but instead want the `target` property to be respected, pass in `browserslist: false` as an option to the plugin as described in the README here: https://github.com/wessberg/rollup-plugin-ts#using-the-plugin-with-typescript-but-without-browserslists

> If no Browserslist can be found, or if you simply don't want to use one, that's completely OK! In such cases, the target property of the nearest tsconfig will be used (or use the Typescript default setting if no such file exists).
>
> You can explicitly request that no Browserslist will be used by setting the browserslist property to false in the plugin options:
>
> ```typescript
> ts({
> 	browserslist: false
> });
> ```

I'm closing this issue, but if this doesn't solve the problem, or if you have any additional feedback, please feel free to comment again.

**Closed by wessberg** 2019-03-09 07:09 UTC
